version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: currency_rate_db
#    volumes:
#      - ./postgres:/data/postgres
    ports:
      - "5432:5432"