spring:
  datasource:
#    url: jdbc:h2:mem:currency_rate_db;MODE=PostgreSQL
    url: jdbc:postgresql://localhost:5432/currency_rate_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml